# Generated by Django 2.0 on 2019-05-11 11:02

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gpic',
            field=stdimage.models.StdImageField(default='goods/default.jpg', upload_to='goods/%Y/%m', verbose_name='商品图片'),
        ),
    ]
