# Generated by Django 2.0 on 2019-05-11 12:10

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_gpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gpic',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(default='goods/319104.jpg', upload_to='goods/%Y/%m', verbose_name='图片'),
        ),
    ]
