# Generated by Django 2.1.7 on 2019-03-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190331_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=2000, verbose_name='内容'),
        ),
    ]
